# Generated by Django 4.1.7 on 2024-02-24 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_playeruser_alter_user_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hitting', models.CharField(max_length=100)),
                ('pitching', models.CharField(max_length=100)),
                ('fielding', models.CharField(max_length=100)),
                ('baserunning', models.CharField(max_length=100)),
                ('mindset', models.CharField(max_length=100)),
                ('nutrition', models.CharField(max_length=100)),
                ('workouts', models.CharField(max_length=100)),
                ('nil', models.CharField(max_length=100, verbose_name='Name, Image, Likeness')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_categories', to='backend.user')),
            ],
        ),
    ]
