# Generated by Django 4.1.7 on 2024-02-24 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_playercategories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playercategories',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_categories', to='backend.playeruser'),
        ),
    ]
