# Generated by Django 4.1.7 on 2024-02-24 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_alter_playercategories_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playercategories',
            old_name='baserunning',
            new_name='category',
        ),
        migrations.RemoveField(
            model_name='playercategories',
            name='fielding',
        ),
        migrations.RemoveField(
            model_name='playercategories',
            name='hitting',
        ),
        migrations.RemoveField(
            model_name='playercategories',
            name='mindset',
        ),
        migrations.RemoveField(
            model_name='playercategories',
            name='nil',
        ),
        migrations.RemoveField(
            model_name='playercategories',
            name='nutrition',
        ),
        migrations.RemoveField(
            model_name='playercategories',
            name='pitching',
        ),
        migrations.RemoveField(
            model_name='playercategories',
            name='workouts',
        ),
    ]
