# Generated by Django 4.1.7 on 2024-02-24 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_rename_baserunning_playercategories_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playercategories',
            old_name='user',
            new_name='player_id',
        ),
    ]
