# Generated by Django 4.1.7 on 2024-02-24 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_rename_user_playercategories_player_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playercategories',
            old_name='player_id',
            new_name='player',
        ),
    ]
