# Generated by Django 4.1.7 on 2024-02-24 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_user_bio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='photo',
            new_name='media1',
        ),
        migrations.AddField(
            model_name='user',
            name='media2',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='media3',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
