# Generated by Django 4.1.7 on 2024-02-25 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_rename_photo_user_media1_user_media2_user_media3'),
    ]

    operations = [
        migrations.AddField(
            model_name='playeruser',
            name='photo',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
