# Generated by Django 4.1.7 on 2024-02-25 23:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_playeruser_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='playercategories',
            name='budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='playercategories',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True, validators=[django.core.validators.MinLengthValidator(30)]),
        ),
    ]
