# Generated by Django 4.1.7 on 2024-03-02 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_playercategories_budget_playercategories_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='coach_category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
