# Generated by Django 4.1.7 on 2024-03-03 00:58

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_user_coach_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='coach_category',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, null=True, size=None),
        ),
    ]
