# Generated by Django 4.1.7 on 2024-03-03 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_alter_user_coach_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='coach_category',
        ),
    ]
