# Generated by Django 4.1.7 on 2024-03-03 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_remove_user_coach_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='coach_category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
