# Generated by Django 4.1.7 on 2024-03-08 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_user_coach_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.DecimalField(decimal_places=2, max_digits=3)),
                ('description', models.TextField()),
                ('playeruser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_as_player', to='backend.playeruser')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_as_user', to='backend.user')),
            ],
        ),
    ]
