# Generated by Django 4.1.7 on 2024-04-09 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
