# Generated by Django 4.1.7 on 2024-04-10 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0018_alter_review_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_id', models.CharField(max_length=255)),
                ('coach_id', models.CharField(max_length=255)),
                ('conversation_sid', models.CharField(max_length=255)),
            ],
        ),
    ]
