# Generated by Django 4.1.7 on 2024-04-23 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0020_mediafiles'),
    ]

    operations = [
        migrations.CreateModel(
            name='PushStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255)),
                ('push_token', models.CharField(blank=True, max_length=255, null=True)),
                ('deviceType', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
