# Generated by Django 4.1.7 on 2024-04-24 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0021_pushstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='pushstatus',
            name='status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
