# Generated by Django 4.1.7 on 2024-04-27 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0022_pushstatus_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='StripeAccounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_account_id', models.CharField(blank=True, max_length=255, null=True)),
                ('coach_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coach_stripe_account_id', to='backend.user')),
            ],
        ),
    ]
