# Generated by Django 4.1.7 on 2024-04-27 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0023_stripeaccounts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stripeaccounts',
            old_name='coach_id',
            new_name='coach',
        ),
    ]
