# Generated by Django 4.1.7 on 2024-04-29 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0024_rename_coach_id_stripeaccounts_coach'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_id', models.CharField(max_length=255)),
                ('coach_id', models.CharField(max_length=255)),
                ('transaction_amount', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
