# Generated by Django 4.1.7 on 2024-04-30 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0025_transactionhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_id', models.CharField(max_length=255)),
                ('coach_id', models.CharField(max_length=255)),
                ('charge_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(default='pending', max_length=20)),
            ],
        ),
    ]
