# Generated by Django 4.1.7 on 2024-04-30 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0026_reviewstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_id', models.CharField(max_length=255)),
                ('coach_id', models.CharField(max_length=255)),
                ('coach_first_name', models.CharField(max_length=100)),
                ('coach_last_name', models.CharField(max_length=100)),
                ('rating', models.IntegerField()),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
