# Generated by Django 4.1.7 on 2024-05-07 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0028_unreadpushcount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UnreadPushCount',
        ),
    ]
