# Generated by Django 4.1.7 on 2024-05-08 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0030_unreadpushcount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unreadpushcount',
            name='unreadPushFromCoach',
            field=models.CharField(default='false', max_length=5),
        ),
        migrations.AlterField(
            model_name='unreadpushcount',
            name='unreadPushFromPlayer',
            field=models.CharField(default='false', max_length=5),
        ),
    ]
