# Generated by Django 4.1.7 on 2024-05-24 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0031_alter_unreadpushcount_unreadpushfromcoach_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionhistory',
            name='transaction_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
