# Generated by Django 4.1.7 on 2024-05-25 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0032_alter_transactionhistory_transaction_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='link1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='link2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='link3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
