"""
Django settings for bp project.

Generated by 'django-admin startproject' using Django 4.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-%y@iwnu*(1q0w8qdzdo3x_$tjg4e%*9!88^$#z16@a%%&(o2p!'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['192.168.0.70', 'localhost', '127.0.0.1', '34.239.108.137', 'Performaxxion-env.eba-c2i5smzi.us-east-1.elasticbeanstalk.com', '.elasticbeanstalk.com', '10.0.0.165', '0.0.0.0', 'cert.performaxxion.com', '3.227.30.199', '.performaxxion.com', '*'] 


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'backend',
    'corsheaders',
    'storages',
]

# Twilio Credentials
TWILIO_ACCOUNT_SID = 'AC5fb0766880f6ceb0e516e1a5d9191246'
TWILIO_AUTH_TOKEN = '13dc07e7dd0bbdece5c4a03c21b16632'
TWILIO_API_KEY = 'SKeb4a43898c8344481957c16d9713ac70'
TWILIO_API_KEY_SECRET = 'mPLK3APeqvxMFxxn7M2gWQ2CPMK1JLfv'
TWILIO_CHAT_SERVICE_SID = 'IS15b7c890ffc640e2abf1cf80e74e6329'

STRIPE_SECRET_KEY = 'sk_test_51P6PYFB4qRatxMAW8Ub5CMufD1J02aCeiux36hhFhqDlTqPuWNCur822l3xlGUToMS2M0wr98uCqkjiIqr3od31k00jxV0aCPq'
STRIPE_PUBLISHABLE_KEY = 'pk_test_51P6PYFB4qRatxMAWLkrZ6hN7npgjVLKcixFIk61QUhEaKEH1mnasr0wQKKnoA4egV5H0zZynRoreRStGGXrYJuEI00EbR2UP5n'

APN_CREDENTIAL_SID = 'CR446f9239ceb27cf37e2e2cb11f8dff45'
#FCM_CREDENTIAL_SID = 'AIzaSyA7mXYjhPOHUNDtN5cpArlj3d6egy5UjX8'

# AWS S3 Settings for Profile Pics / Vids
AWS_ACCESS_KEY_ID = 'AKIAS74GIVSG4OQA4VXW'
AWS_SECRET_ACCESS_KEY = '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'
AWS_STORAGE_BUCKET_NAME = 'paxphotos'
AWS_S3_CUSTOM_DOMAIN = f'{AWS_STORAGE_BUCKET_NAME}.s3.amazonaws.com'
AWS_S3_OBJECT_PARAMETERS = {'CacheControl': 'max-age=86400'}
AWS_LOCATION = ''
AWS_DEFAULT_ACL = 'public-read'  # Ensure this aligns with your security policies

AWS_STORAGE_BUCKET_NAME2 = 'twiliomediafiles'


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
]

#SECURE_SSL_REDIRECT = True


ROOT_URLCONF = 'bp.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'bp.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'postgres',
        'USER': 'admin1',
        'PASSWORD': 'admin123',
        'HOST': 'testdb1.chuaaau220ua.us-east-1.rds.amazonaws.com',
        'PORT': '5432',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CORS_ALLOW_ALL_ORIGINS = True



FILE_UPLOAD_HANDLERS = [
    'django.core.files.uploadhandler.TemporaryFileUploadHandler',
]


LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
        },
    },
    'loggers': {
        '': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': True,
        },
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        # Customize the logger for your specific app if needed
        'backend': {
            'handlers': ['console'],
            'level': 'DEBUG', # Use DEBUG or INFO as needed
            'propagate': False,
        },
    },
}

'''# Security settings
SECURE_SSL_REDIRECT = True
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True

# HSTS settings
SECURE_HSTS_SECONDS = 31536000
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_HSTS_PRELOAD = True

# If behind a proxy like NGINX, add this:
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')'''

# settings.py

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.hostinger.com'  # This is the SMTP host for Hostinger
EMAIL_PORT = 587  # Port for TLS, use 465 for SSL
EMAIL_USE_TLS = True  # Use TLS, set to False if using SSL and change port to 465
EMAIL_HOST_USER = 'support@performaxxion.com'  # Your Hostinger email address
EMAIL_HOST_PASSWORD = 'JaidoTrav123!'  # Your Hostinger email password
DEFAULT_FROM_EMAIL = 'Performaxxion Support <support@performaxxion.com>'
